[package]
name = "meli"
version = "0.1.0"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
edition = "2018"

[[bin]]
name = "meli"
path = "src/bin.rs"

[dependencies]
chan = "0.1.21"
chan-signal = "0.3.1"
nix = "*"
melib = { path = "melib", version = "*" }

ui = { path = "ui", version = "*" }

[profile.release]
lto = true
#debug = true

[workspace]
members = ["melib", "ui"]

[features]
default = []
debug_log = []
