[package]
name = "meli"
version = "0.1.0"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]

[lib]
name = "melib"
path = "src/lib.rs"

[[bin]]
name = "meli"
path = "src/bin.rs"

[dependencies]
chrono = "0.4"
xdg = "2.1.0"
config = "0.6"
serde_derive = "^1.0.8"
serde = "^1.0.8"
nom = "3.2.0"
memmap = "*"
base64 = "*"
crossbeam = "^0.3.0"
fnv = "1.0.3"
encoding = "0.2.33"
bitflags = "1.0"
notify = "4.0.1"

[dependencies.ncurses]
features = ["wide"]
optional = false
version = "5.86.0"

[profile.release]
#lto = true
debug = true
