[package]
name = "meli"
version = "0.3.1"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
edition = "2018"

[[bin]]
name = "meli"
path = "src/bin.rs"

[dependencies]
xdg = "2.1.0"
crossbeam = "0.7.2"
signal-hook = "0.1.10"
nix = "*"
melib = { path = "melib", version = "*" }
ui = { path = "ui", version = "*" }
#enable for debug tracing logs
#melib = { path = "melib", version = "*", features=["debug-tracing",] }
#ui = { path = "ui", version = "*", features=["debug-tracing",] }

[profile.release]
lto = true
debug = false

[workspace]
members = ["melib", "ui", "debug_printer", "testing", "text_processing"]

[features]
default = []
# Print tracing logs as meli runs in stderr
#
# enable for debug tracing logs
# debug-tracing = []
