[package]
name = "meli"
version = "0.4.1"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
edition = "2018"

[[bin]]
name = "meli"
path = "src/bin.rs"

[dependencies]
xdg = "2.1.0"
crossbeam = "0.7.2"
signal-hook = "0.1.12"
signal-hook-registry = "1.2.0"
nix = "0.16.1"
melib = { path = "melib", version = "*" }
ui = { path = "ui", version = "*" }

[profile.release]
lto = true
debug = false

[workspace]
members = ["melib", "ui", "debug_printer", "testing", "text_processing"]

[features]
default = []
notmuch = ["melib/notmuch_backend", "ui/notmuch"]
jmap = ["melib/jmap_backend",]

# Print tracing logs as meli runs in stderr
# enable for debug tracing logs: build with --features=debug-tracing
debug-tracing = ["melib/debug-tracing", "ui/debug-tracing"]
