[package]
name = "testing"
version = "0.0.1"  #:version
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
workspace = ".."
edition = "2018"

[[bin]]
name = "emailparse"
path = "src/email_parse.rs"
[[bin]]
name = "linebreak"
path = "src/linebreak.rs"


[dependencies]
melib = { path = "../melib", version = "*" }
text_processing = { path = "../text_processing", version = "*" }
