[package]
name = "testing"
version = "0.0.1"  #:version
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
workspace = ".."

[[bin]]
name = "emailparse"
path = "src/email_parse.rs"


[dependencies]
melib = { path = "../melib", version = "*" }
