[package]
name = "text_processing"
version = "0.0.1"  #:version
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
workspace = ".."
edition = "2018"

[dependencies]
unicode-segmentation = "1.2.1"
