[package]
name = "text_processing"
version = "0.3.0"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
workspace = ".."
edition = "2018"
build = "build.rs"

[dependencies]
unicode-segmentation = "1.2.1"
