[package]
name = "melib"
version = "0.3.0"
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
workspace = ".."
edition = "2018"

[dependencies]
bitflags = "1.0"
chrono = { version = "0.4", features = ["serde"] }
crossbeam = "0.7.2"
data-encoding = "2.1.1"
encoding = "0.2.33"
fnv = "1.0.3"
memmap = "0.5.2"
nom = "3.2.0"
notify = "4.0.1"
notify-rust = "^3"
termion = "1.5.1"
xdg = "2.1.0"
native-tls = "0.2"
serde = "1.0.71"
serde_derive = "1.0.71"
bincode = "1.0.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
text_processing = { path = "../text_processing", version = "*" }
libc = {version = "0.2.59", features = ["extra_traits",]}
