[package]
name = "melib"
version = "0.0.1"  #:version
authors = ["Manos Pitsidianakis <el13635@mail.ntua.gr>"]
workspace = ".."
edition = "2018"

[dependencies]
bitflags = "1.0"
chan = "0.1.21"
chrono = { version = "0.4", features = ["serde"] }
crossbeam = "^0.3.0"
data-encoding = "2.1.1"
encoding = "0.2.33"
fnv = "1.0.3"
memmap = "0.5.2"
nom = "3.2.0"
notify = "4.0.1"
notify-rust = "^3"
termion = "1.5.1"
xdg = "2.1.0"
serde = "1.0.71"
serde_derive = "1.0.71"
bincode = "1.0.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
unicode-segmentation = "1.2.1" # >:c
