[package]
name = "melib"
version = "0.7.2"
authors = ["Manos Pitsidianakis <epilys@nessuent.xyz>"]
workspace = ".."
edition = "2018"
build = "build.rs"

homepage = "https://meli.delivery"
repository = "https://git.meli.delivery/meli/meli.git"
description = "mail library"
keywords = ["mail", "mua", "maildir", "imap", "jmap"]
categories = [ "email", "parser-implementations"]
license = "GPL-3.0-or-later"
readme = "README.md"

[lib]
name = "melib"
path = "src/lib.rs"

[dependencies]
bitflags = "1.0"
data-encoding = "2.1.1"
encoding = "0.2.33"
nom = { version = "5" }

indexmap = { version = "^1.5", features = ["serde-1", ] }
notify = { version = "4.0.15", optional = true }
xdg = "2.1.0"
native-tls = { version ="0.2.3", optional=true }
serde = { version = "1.0.71", features = ["rc", ] }
serde_derive = "1.0.71"
bincode = "^1.3.0"
uuid = { version = "^1", features = ["serde", "v4", "v5"] }

unicode-segmentation = { version = "1.2.1", optional = true }
libc = {version = "0.2.125", features = ["extra_traits",]}
isahc = { version = "^1.7", optional = true, default-features = false, features = ["http2", "json", "text-decoding"]}
serde_json = { version = "1.0", optional = true, features = ["raw_value",] }
smallvec = { version = "^1.5.0", features = ["serde", ] }
nix = "^0.24"
rusqlite = {version = "^0.27", optional = true }

libloading = "^0.7"
futures = "0.3.5"
smol = "1.0.0"
async-stream = "^0.3"
base64 = { version = "^0.13", optional = true }
flate2 = { version = "1.0.16", optional = true }
xdg-utils = "^0.4.0"

[features]
default = ["unicode_algorithms", "imap_backend", "maildir_backend", "mbox_backend", "vcard", "sqlite3", "smtp", "deflate_compression"]

debug-tracing = []
deflate_compression = ["flate2", ]
gpgme = []
http = ["isahc"]
http-static = ["isahc", "isahc/static-curl"]
imap_backend = ["tls"]
jmap_backend = ["http", "serde_json"]
maildir_backend = ["notify"]
mbox_backend = ["notify"]
notmuch_backend = []
smtp = ["tls", "base64"]
sqlite3 = ["rusqlite", ]
tls = ["native-tls"]
unicode_algorithms = ["unicode-segmentation"]
vcard = []
