[package]
name = "ui"
version = "0.0.1"  #:version
authors = []
workspace = ".."

[dependencies]
melib = { path = "../melib", version = "*" }
termion = "1.5.1"
chan = "0.1.21"
notify = "4.0.1"
notify-rust = "^3"
nom = "3.2.0"
chan-signal = "0.3.1"
mime_apps = { path = "../../mime_apps", version = "*" }

uuid = { version = "0.6", features = ["serde", "v4"] }
linkify = "0.3.1"
